### ISSUE TITLE
Add a prerequisite file

### ISSUE THREAD

**Issue by graboskyc** [mpw07458/K8S-Deploy#1]
Create a bash script with the apt-get installs/yum installs of all CLI tools used

**Comment by mpw07458** [comment]
Sorry just saw this today, this is definitely a practical comment, you are correct some of the scripts are here some are not, I need to identify the scripts and steps, and the order of steps to install. We will see what you say after the demo tomorrow.

**Comment by mpw07458** [comment]
README.md should fix this I suggest close on this one
https://github.com/mpw07458/K8S-Deploy/blob/master/README.md

**Comment by mpw07458** [comment]
requirements.txt is there
for v0.933 required packages are:
docker
kubernetes
openshift
json
subprocess
sys
pprint
